name: ðŸ’… Lint Checks

on: [merge_group, pull_request]

jobs:
  lint-css:
    runs-on: ubuntu-latest
    name: CSS valid
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm turbo lint:css

  lint-js:
    runs-on: ubuntu-latest
    name: JS valid
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm turbo lint:js

  lint-ts:
    runs-on: ubuntu-latest
    name: TS valid
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm turbo lint:ts
